const $=s=>document.querySelector(s),video=$('#camera'),canvas=$('#screen'),ctx=canvas.getContext('2d',{alpha:false});
const input=document.createElement('canvas'),ix=input.getContext('2d');input.width=640;input.height=480;
const version='0.5.1675471629',cdn=`https://cdn.jsdelivr.net/npm/@mediapipe/holistic@${version}/`;
const challenges=[['peace','✌️','سوّ علامة السلام','شخصية رئيسية'],['open','😮','افتح فمك','يوم شفت الفاتورة'],['tilt','🙃','ميّل راسك','المخ يعيد التشغيل'],['up','🙌','ارفع يديك','الراتب وصل!'],['pinch','🤏','قرّب السبابة والإبهام','هذا اللي بقى من الراتب'],['portal','👐','قرّب يديك من بعض','دخلت عالم ثاني']];
const effects=['none','hue-rotate(300deg) saturate(2)','grayscale(1) contrast(2)','hue-rotate(100deg) saturate(2)','sepia(.7) saturate(2)','invert(1)','hue-rotate(180deg) contrast(1.4)','saturate(3)','sepia(1)','contrast(1.6)'];
let stream,tracker,active=false,starting=false,generation=0,raf,latest={},lastResult=0,lastDetect=0,busy=false,round=0,points=0,held=0,lastCue=0,rewardUntil=0,caption='',effect=0,portalArmed=true;
function deadline(p,ms,label){let t;return Promise.race([p,new Promise((_,reject)=>t=setTimeout(()=>reject(Error(label)),ms))]).finally(()=>clearTimeout(t))}
function script(root){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=root+'holistic.js';s.onload=resolve;s.onerror=()=>reject(Error('تعذّر تحميل نظام التتبع'));document.head.append(s)})}
function stop(){generation++;active=false;busy=true;cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;const old=tracker;tracker=null;old?.close?.().catch(()=>{});$('#hud').hidden=true}
function failure(e){stop();$('#errorText').textContent=e.name==='NotAllowedError'?'اسمح بالكاميرا من إعدادات المتصفح.':e.message;$('#error').hidden=false}
async function start(){if(starting)return;starting=true;stop();const token=generation;$('#start').disabled=true;$('#start').textContent='لحظة…';$('#error').hidden=true;try{if(!isSecureContext&&location.protocol!=='file:')throw Error('افتح الرابط عبر HTTPS.');if(!navigator.mediaDevices?.getUserMedia)throw Error('افتح الرابط مباشرة في Safari أو Chrome عبر HTTPS.');stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}}});video.srcObject=stream;await video.play();await deadline(new Promise(resolve=>{if(video.videoWidth)return resolve();video.addEventListener('loadeddata',resolve,{once:true})}),10000,'الكاميرا لا ترسل صورة');$('#home').hidden=true;$('#hud').hidden=false;$('#prompt').textContent='تحميل اللعبة…';$('#hint').textContent='خلّ وجهك ويديك داخل الكادر';active=true;round=points=held=effect=0;latest={};lastResult=0;lastCue=0;rewardUntil=0;portalArmed=true;draw();
 const roots=location.protocol==='file:'?[cdn]:[new URL('./vendor/holistic/',document.baseURI).href,cdn];let error;for(const root of roots){if(token!==generation)return;let candidate;try{await deadline(script(root),15000,'تعذّر تحميل التتبع');candidate=new Holistic({locateFile:f=>root+f});candidate.setOptions({modelComplexity:0,smoothLandmarks:true,enableSegmentation:false,refineFaceLandmarks:false,minDetectionConfidence:.5,minTrackingConfidence:.5});candidate.onResults(r=>{if(token!==generation||tracker!==candidate)return;latest=r;lastResult=performance.now();processResult(r,lastResult)});tracker=candidate;await deadline(candidate.send({image:video}),45000,'تعذّر تحميل نموذج اللعبة. تحقق من الإنترنت وملفات vendor.');if(token!==generation)return;showChallenge();busy=false;lastDetect=performance.now();return}catch(e){error=e;tracker=null;candidate?.close?.().catch(()=>{})}}throw error;
 }catch(e){if(token===generation)failure(e)}finally{starting=false;$('#start').disabled=false;$('#start').textContent='يلا نلعب ↗'}}
function showChallenge(){const item=challenges[round%challenges.length];$('#symbol').textContent=item[1];$('#prompt').textContent=item[2];$('#score').textContent=`${points} / 6`;$('#hold').value=0}
function processResult(r,now){const cues=Cues.read(r),delta=Math.min(200,lastCue?now-lastCue:0);lastCue=now;if(cues.gap>.30)portalArmed=true;if(now<rewardUntil)return;const target=challenges[round%challenges.length];let matched=cues[target[0]];if(target[0]==='portal')matched&&=portalArmed;held=matched?held+delta:0;$('#hold').value=Math.min(1,held/450);$('#hint').textContent=!r.faceLandmarks?.length?'خلّ وجهك ظاهر، وابتعد شوي':cues.hands.length?'':'أظهر يديك عند طلب الإشارة';if(held<450)return;if(target[0]==='portal')portalArmed=false;held=0;points++;caption=target[3];effect=1+Math.floor(Math.random()*(effects.length-1));rewardUntil=now+2000;$('#prompt').textContent=points===6?'أسطورة! جولة جديدة؟':'ضبطتها!';$('#symbol').textContent='✨';$('#score').textContent=`${points} / 6`;round++;setTimeout(()=>{if(!active)return;if(points===6)points=0;showChallenge()},2000)}
function draw(){if(!active)return;const now=performance.now(),w=innerWidth,h=innerHeight,d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*d)||canvas.height!==Math.round(h*d)){canvas.width=Math.round(w*d);canvas.height=Math.round(h*d)}ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle='#101019';ctx.fillRect(0,0,w,h);const scale=Math.min(w/video.videoWidth,h/video.videoHeight),dw=video.videoWidth*scale,dh=video.videoHeight*scale,dx=(w-dw)/2,dy=(h-dh)/2;ctx.save();ctx.filter=effects[effect];ctx.translate(w,0);ctx.scale(-1,1);ctx.drawImage(video,dx,dy,dw,dh);ctx.restore();
 const fresh=now-lastResult<700;const hands=fresh?[latest.leftHandLandmarks,latest.rightHandLandmarks].filter(Boolean):[];const map=p=>({x:w-(dx+p.x*dw),y:dy+p.y*dh});for(const hand of hands)for(const i of [4,8]){const p=map(hand[i]);ctx.fillStyle='#d7fc70';ctx.beginPath();ctx.arc(p.x,p.y,4,0,7);ctx.fill()}
 if(hands.length===2){const sorted=hands.slice().sort((a,b)=>map(a[9]).x-map(b[9]).x);const p=[map(sorted[0][8]),map(sorted[1][8]),map(sorted[1][4]),map(sorted[0][4])];ctx.save();ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);p.slice(1).forEach(v=>ctx.lineTo(v.x,v.y));ctx.closePath();ctx.strokeStyle='#d7fc70';ctx.lineWidth=3;ctx.stroke();ctx.clip();ctx.filter=effects[(effect+1)%effects.length];ctx.translate(w,0);ctx.scale(-1,1);ctx.drawImage(video,dx,dy,dw,dh);ctx.restore()}
 if(now<rewardUntil){ctx.save();ctx.textAlign='center';ctx.font=`bold ${Math.min(38,w/18)}px Arial`;ctx.lineWidth=7;ctx.strokeStyle='#000';ctx.fillStyle='#fff';ctx.strokeText(caption,w/2,h*.25,w*.9);ctx.fillText(caption,w/2,h*.25,w*.9);ctx.restore()}
 if(tracker&&lastResult&&!busy&&now-lastDetect>100&&!document.hidden){busy=true;lastDetect=now;const engine=tracker,token=generation;input.height=Math.round(640*video.videoHeight/video.videoWidth);ix.drawImage(video,0,0,input.width,input.height);deadline(Promise.resolve().then(()=>engine.send({image:input})),15000,'توقف التتبع. أعد المحاولة.').catch(e=>{if(token===generation)failure(e)}).finally(()=>{if(token===generation)busy=false})}raf=requestAnimationFrame(draw)}
$('#start').onclick=start;$('#retry').onclick=start;$('#exit').onclick=()=>{stop();$('#home').hidden=false};$('#back').onclick=()=>{$('#error').hidden=true;$('#home').hidden=false};addEventListener('pagehide',stop);
