/* MAZ LAB 10 — camera and tracker have independent lifecycles. */
const release='0.4.1646424915';
let trackerReady=false, starting=false, packet=0, gesturePacket=-1;
const originalPortal=portal;
let diamondHold=0,diamondLocked=false,placedDiamonds=[],energyTrails=[];
worlds.push(...[
 ['غروب طوكيو','sepia(.3) saturate(1.8) hue-rotate(315deg)'],['سينما','contrast(1.25) saturate(.65)'],['أرشيف 1999','sepia(.55) contrast(.9)'],['أبيض وأسود','grayscale(1) contrast(1.3)'],['أشعة سينية','invert(1) grayscale(1)'],['حلم وردي','sepia(.4) hue-rotate(290deg) saturate(2)'],['مريخي','hue-rotate(90deg) saturate(2)'],['أزرق كهربائي','hue-rotate(180deg) saturate(2)'],['ذهبي','sepia(1) saturate(2)'],['كاميرا مراقبة','grayscale(1) contrast(1.8) brightness(.8)'],['باستيل','contrast(.8) brightness(1.15) saturate(.7)'],['حبر','grayscale(1) contrast(3)'],['حلو وحامض','hue-rotate(45deg) saturate(3)'],['ليلة بنفسجية','hue-rotate(230deg) contrast(1.3)'],['ألوان مقلوبة','invert(1)'],['فلاش','brightness(1.3) contrast(1.2)'],['فيلم قديم','sepia(.8) saturate(.5) contrast(1.4)'],['توهج','brightness(1.1) saturate(1.9)'],['بارد','hue-rotate(160deg) saturate(.7)']
].map(([name,filter])=>({name,filter})),
 {name:'البوابة الحيّة',filter:'contrast(1.35) saturate(2.8)',animated:true},
 {name:'بوابة الكابوس',filter:'grayscale(.85) contrast(2.4) brightness(.55) sepia(.7) hue-rotate(315deg)',scary:true}
);
document.querySelector('.intro .eyebrow').textContent='MAZ // LAB — CAMERA PLAYGROUND';
document.querySelector('.intro h1').innerHTML='وجهك.<br>عالم آخر.';
document.querySelector('.intro-copy').textContent='ارفع يديك أمام الكاميرا، قرّبهما لتغيير العالم، ثم باعد بينهما لتشاهد النتيجة.';
document.querySelector('.bootline').textContent='الإصدار 10 / مختبر العوالم';
document.querySelector('#startBtn').innerHTML='افتح الكاميرا ↗';
document.querySelector('.privacy').textContent='الكاميرا تبقى على جهازك. لا حساب ولا رفع فيديو.';
const statusEl=document.createElement('span');statusEl.id='trackingStatus';statusEl.className='sr-only';statusEl.setAttribute('aria-live','polite');document.querySelector('main').append(statusEl);
function timeout(promise,ms,label){let timer;return Promise.race([promise,new Promise((_,reject)=>timer=setTimeout(()=>reject(new Error(label)),ms))]).finally(()=>clearTimeout(timer))}
function loadTrackerScript(root){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=root+'hands.js';s.onload=resolve;s.onerror=()=>reject(new Error('تعذّر تحميل hands.js'));document.head.append(s)})}
let trackingStart=null;
async function startTracking(){if(trackingStart)return trackingStart;trackingStart=(async()=>{trackerReady=false;statusEl.textContent='تحميل تتبع اليدين…';const roots=location.protocol==='file:'?[]:[new URL('./',document.baseURI).href];roots.push(`https://cdn.jsdelivr.net/npm/@mediapipe/hands@${release}/`,`https://unpkg.com/@mediapipe/hands@${release}/`);let error;
 for(const root of roots){let candidate;try{await timeout(loadTrackerScript(root),15000,'انتهت مهلة تحميل التتبع');candidate=new Hands({locateFile:f=>root+f});candidate.setOptions({maxNumHands:2,modelComplexity:0,selfieMode:false,minDetectionConfidence:.45,minTrackingConfidence:.45});candidate.onResults(r=>{if(landmarker!==candidate)return;window.__lastHands=r.multiHandLandmarks||[];packet++;statusEl.textContent=`التتبع يعمل • ${window.__lastHands.length} يد`});landmarker=candidate;await timeout(candidate.send({image:video}),30000,'انتهت مهلة تحميل النموذج');trackerReady=true;processing=false;return;}catch(e){error=e;landmarker=null;window.__lastHands=[];candidate?.close?.().catch(()=>{});}}
 statusEl.textContent='التتبع غير متاح: '+(error?.message||'خطأ غير معروف')+' — يمكنك استخدام الفلاتر باللمس';})();try{await trackingStart}finally{trackingStart=null}}
init=async function(){if(starting||running)return;starting=true;show(ui.intro,false);show(ui.error,false);show(ui.loading);try{if(!window.isSecureContext&&location.protocol!=='file:')throw new Error('افتح الموقع عبر HTTPS لتشغيل الكاميرا.');if(!navigator.mediaDevices?.getUserMedia)throw new Error('افتح الرابط مباشرة في Safari أو Chrome عبر HTTPS.');await startCamera();await timeout(new Promise(resolve=>{if(video.videoWidth)return resolve();video.addEventListener('loadeddata',resolve,{once:true})}),10000,'الكاميرا لا ترسل صورة');running=true;show(ui.loading,false);document.querySelector('.socials').classList.add('hidden');fit();loop();startTracking();}catch(e){show(ui.loading,false);show(ui.error);ui.errorText.textContent=e.name==='NotAllowedError'?'اسمح بالكاميرا من إعدادات الموقع ثم أعد المحاولة.':e.message;}finally{starting=false}};
document.querySelector('#startBtn').onclick=init;document.querySelector('#retryBtn').onclick=init;
portal=(...args)=>{if(packet===gesturePacket){const old=closeFrames;const out=originalPortal(...args);closeFrames=old;return out}gesturePacket=packet;return originalPortal(...args)};
function gap(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function handOpen(lm){const palm=gap(lm[0],lm[9]);return [8,12,16,20].filter((tip,n)=>gap(lm[tip],lm[0])>gap(lm[[6,10,14,18][n]],lm[0])*1.16).length>=3&&gap(lm[4],lm[5])>palm*.65}
function neonLine(points,color,width=2,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.shadowBlur=16;ctx.shadowColor=color;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.stroke();ctx.restore()}
function drawShield(lm,box,w,now){const c=mapPoint(lm,9,box,w),wrist=mapPoint(lm,0,box,w),radius=Math.max(62,Math.min(150,gap(c,wrist)*2.2)),spin=now/900,ring=[];for(let i=0;i<7;i++){const a=spin+i*Math.PI*2/6;ring.push({x:c.x+Math.cos(a)*radius,y:c.y+Math.sin(a)*radius*1.18})}ctx.save();ctx.fillStyle='rgba(0,190,255,.09)';polyPath(ring);ctx.fill();neonLine(ring,'#56eaff',3,.9);for(let i=0;i<6;i++)neonLine([c,ring[i]],'#32bfff',1,.28);for(let r=.35;r<1;r+=.27){const inner=ring.slice(0,6).map(p=>({x:c.x+(p.x-c.x)*r,y:c.y+(p.y-c.y)*r}));inner.push(inner[0]);neonLine(inner,'#7ff5ff',1,.22)}ctx.restore()}
function drawDiamondShape(d,now){const pulse=1+.08*Math.sin(now/130+d.phase),rx=d.size*pulse,ry=d.size*1.28*pulse,pts=[{x:d.x,y:d.y-ry},{x:d.x+rx,y:d.y},{x:d.x,y:d.y+ry},{x:d.x-rx,y:d.y},{x:d.x,y:d.y-ry}];ctx.save();ctx.globalCompositeOperation='screen';ctx.fillStyle=`rgba(20,170,255,${Math.min(.18,d.life/80*.18)})`;polyPath(pts);ctx.fill();neonLine(pts,'#8ff8ff',4,Math.min(1,d.life/30));const core=pts.map(p=>({x:d.x+(p.x-d.x)*.55,y:d.y+(p.y-d.y)*.55}));neonLine(core,'#287dff',2,.8);ctx.restore()}
function drawHardLight(lms,box,w,h,now){
 for(const lm of lms){if(handOpen(lm))drawShield(lm,box,w,now);const a=mapPoint(lm,4,box,w),b=mapPoint(lm,8,box,w),scale=Math.max(35,gap(mapPoint(lm,0,box,w),mapPoint(lm,9,box,w)));if(gap(a,b)<scale*.48){const c={x:(a.x+b.x)/2,y:(a.y+b.y)/2};energyTrails.push({x:c.x,y:c.y,life:1});ctx.save();ctx.fillStyle='#d8ffff';ctx.shadowBlur=28;ctx.shadowColor='#00c8ff';ctx.beginPath();ctx.arc(c.x,c.y,9+5*Math.sin(now/70),0,7);ctx.fill();ctx.restore()}}
 energyTrails=energyTrails.filter(t=>{t.life-=.045;ctx.save();ctx.globalAlpha=Math.max(0,t.life);ctx.fillStyle='#3ce8ff';ctx.shadowBlur=18;ctx.shadowColor='#167dff';ctx.beginPath();ctx.arc(t.x,t.y,3+t.life*8,0,7);ctx.fill();ctx.restore();return t.life>0}).slice(-70);
 if(lms.length===2){const sorted=lms.slice().sort((a,b)=>mapPoint(a,9,box,w).x-mapPoint(b,9,box,w).x),li=mapPoint(sorted[0],8,box,w),ri=mapPoint(sorted[1],8,box,w),lt=mapPoint(sorted[0],4,box,w),rt=mapPoint(sorted[1],4,box,w),handScale=(gap(mapPoint(sorted[0],0,box,w),mapPoint(sorted[0],9,box,w))+gap(mapPoint(sorted[1],0,box,w),mapPoint(sorted[1],9,box,w)))/2;const forming=gap(li,ri)<handScale*.8&&gap(lt,rt)<handScale*.8&&gap({x:(li.x+ri.x)/2,y:(li.y+ri.y)/2},{x:(lt.x+rt.x)/2,y:(lt.y+rt.y)/2})>handScale*.55;if(forming){diamondHold++;const top={x:(li.x+ri.x)/2,y:(li.y+ri.y)/2},bottom={x:(lt.x+rt.x)/2,y:(lt.y+rt.y)/2},center={x:(top.x+bottom.x)/2,y:(top.y+bottom.y)/2};drawDiamondShape({x:center.x,y:center.y,size:Math.max(32,gap(top,bottom)*.55),life:80,phase:0},now);if(diamondHold>6&&!diamondLocked){placedDiamonds.push({x:center.x,y:center.y,size:Math.max(38,gap(top,bottom)*.62),life:480,phase:Math.random()*6});placedDiamonds=placedDiamonds.slice(-3);diamondLocked=true;burst(center)}}else{diamondHold=0;diamondLocked=false}}
 placedDiamonds=placedDiamonds.filter(d=>{d.life--;drawDiamondShape(d,now);return d.life>0})
}
loop=function(now=performance.now()){if(!running)return;const {w,h}=size();ctx.save();ctx.fillStyle='#090b10';ctx.fillRect(0,0,w,h);const box=drawVideo(w,h);ctx.restore();
 if(trackerReady&&!processing&&video.readyState>=2&&now-lastDetect>80){lastDetect=now;processing=true;const active=landmarker;timeout(Promise.resolve().then(()=>active.send({image:video})),12000,'توقف التتبع — اضغط إعادة التتبع').catch(e=>{trackerReady=false;window.__lastHands=[];statusEl.textContent=e.message}).finally(()=>processing=false)}
 const lms=window.__lastHands||[];drawTracking(lms,box,w);if(lms.length===2)portal(lms,box,w,h,now);else closeFrames=0;drawHardLight(lms,box,w,h,now);
 drawParticles();frameHandle=requestAnimationFrame(loop)};
document.querySelector('#flipBtn').onclick=async()=>{if(!running)return;try{await startCameraFlip()}catch(e){statusEl.textContent=e.message}};
async function startCameraFlip(){facing=facing==='user'?'environment':'user';await startCamera();window.__lastHands=[]}
